export const tool = {
  name: 'domotz_agents',
  description: 'Manage Domotz collectors (agents). Use "action" to specify the operation. Actions: list, count, get, delete, activity_log, connection_consumption, vpn_connections, create_vpn, delete_vpn, status_history, speed_test_history, ip_conflicts, rtd_stats, network_topology, uptime, list_uptime_all, variables, count_variables, variable_history, move, eyes_usage, metric_usage, device_applications, count_device_applications, device_variables, count_device_variables, eyes_snmp, eyes_tcp, unmanaged_devices, external_host, dhcp_discovery',
  inputSchema: {
    type: 'object',
    properties: {
      action: {
        type: 'string',
        enum: [
          'list', 'count', 'get', 'delete', 'activity_log',
          'connection_consumption', 'vpn_connections', 'create_vpn', 'delete_vpn',
          'status_history', 'speed_test_history', 'ip_conflicts', 'rtd_stats',
          'network_topology', 'uptime', 'list_uptime_all',
          'variables', 'count_variables', 'variable_history',
          'move', 'eyes_usage', 'metric_usage',
          'device_applications', 'count_device_applications',
          'device_variables', 'count_device_variables',
          'eyes_snmp', 'eyes_tcp', 'unmanaged_devices',
          'external_host', 'dhcp_discovery'
        ],
        description: 'The operation to perform'
      },
      agent_id: { type: 'integer', description: 'Agent/Collector ID' },
      variable_id: { type: 'integer', description: 'Variable ID' },
      vpn_session_id: { type: 'integer', description: 'VPN Session ID' },
      team_id: { type: 'integer', description: 'Team ID (for move action)' },
      from: { type: 'string', description: 'Start time for time series (default: one week ago)' },
      to: { type: 'string', description: 'End time for time series (default: now)' },
      type: { type: 'string', description: 'Activity log type filter' },
      page_size: { type: 'number', description: 'Max items to return (1-1000)' },
      page_number: { type: 'number', description: 'Page number, 0-indexed' },
      display_name: { type: 'string', description: 'Filter by display name (case insensitive)' },
      team_name: { type: 'string', description: 'Filter by team name' },
      value: { type: 'string', description: 'Filter variables by value' },
      path: { type: 'string', description: 'Filter variables by path' },
      sort_by: { type: 'string', description: 'Sort field for variables' },
      sorting_direction: { type: 'string', description: 'Sort direction (asc/desc)' },
      has_history: { type: 'boolean', description: 'Filter by has_history field' },
      metric: { type: 'string', description: 'Filter by metric' },
      name: { type: 'string', description: 'Filter applications by name' },
      device_ids: { type: 'string', description: 'Filter applications by device IDs' },
      body: { type: 'object', description: 'Request body (JSON object)' }
    },
    required: ['action']
  }
};

export const actions = {
  list:                      { method: 'GET',    url: '/agent',                                           queryParams: ['page_size', 'page_number', 'display_name', 'team_name'] },
  count:                     { method: 'HEAD',   url: '/agent',                                           queryParams: ['display_name', 'team_name'] },
  get:                       { method: 'GET',    url: '/agent/{agent_id}' },
  delete:                    { method: 'DELETE',  url: '/agent/{agent_id}' },
  activity_log:              { method: 'GET',    url: '/agent/{agent_id}/activity-log',                   queryParams: ['from', 'to', 'type'] },
  connection_consumption:    { method: 'GET',    url: '/agent/{agent_id}/connection/consumption' },
  vpn_connections:           { method: 'GET',    url: '/agent/{agent_id}/connection/vpn-session' },
  create_vpn:                { method: 'POST',   url: '/agent/{agent_id}/connection/vpn-session',         hasBody: true },
  delete_vpn:                { method: 'DELETE',  url: '/agent/{agent_id}/connection/vpn-session/{vpn_session_id}' },
  status_history:            { method: 'GET',    url: '/agent/{agent_id}/history/network/event',          queryParams: ['from', 'to'] },
  speed_test_history:        { method: 'GET',    url: '/agent/{agent_id}/history/network/speed',          queryParams: ['from', 'to'] },
  ip_conflicts:              { method: 'GET',    url: '/agent/{agent_id}/ip-conflict' },
  rtd_stats:                 { method: 'GET',    url: '/agent/{agent_id}/device/rtd' },
  network_topology:          { method: 'GET',    url: '/agent/{agent_id}/network-topology' },
  uptime:                    { method: 'GET',    url: '/agent/{agent_id}/uptime',                         queryParams: ['from', 'to'] },
  list_uptime_all:           { method: 'GET',    url: '/agent/uptime',                                    queryParams: ['from', 'to'] },
  variables:                 { method: 'GET',    url: '/agent/{agent_id}/variable',                       queryParams: ['page_size', 'page_number', 'value', 'path', 'sort_by', 'sorting_direction', 'has_history', 'metric'] },
  count_variables:           { method: 'HEAD',   url: '/agent/{agent_id}/variable',                       queryParams: ['value', 'path', 'has_history', 'metric'] },
  variable_history:          { method: 'GET',    url: '/agent/{agent_id}/variable/{variable_id}/history', queryParams: ['from', 'to'] },
  move:                      { method: 'PUT',    url: '/agent/{agent_id}/ownership/team/{team_id}' },
  eyes_usage:                { method: 'GET',    url: '/agent/{agent_id}/eye-statistics' },
  metric_usage:              { method: 'GET',    url: '/agent/{agent_id}/metric-statistics' },
  device_applications:       { method: 'GET',    url: '/agent/{agent_id}/device/application',             queryParams: ['page_size', 'page_number', 'name', 'device_ids'] },
  count_device_applications: { method: 'HEAD',   url: '/agent/{agent_id}/device/application',             queryParams: ['name', 'device_ids'] },
  device_variables:          { method: 'GET',    url: '/agent/{agent_id}/device/variable',                queryParams: ['page_size', 'page_number', 'value', 'path', 'sort_by', 'sorting_direction', 'has_history', 'metric'] },
  count_device_variables:    { method: 'HEAD',   url: '/agent/{agent_id}/device/variable',                queryParams: ['value', 'path', 'has_history', 'metric'] },
  eyes_snmp:                 { method: 'GET',    url: '/agent/{agent_id}/device/eye/snmp' },
  eyes_tcp:                  { method: 'GET',    url: '/agent/{agent_id}/device/eye/tcp' },
  unmanaged_devices:         { method: 'GET',    url: '/agent/{agent_id}/device/monitoring-state/unmanaged' },
  external_host:             { method: 'POST',   url: '/agent/{agent_id}/device/external-host',           hasBody: true },
  dhcp_discovery:            { method: 'PUT',    url: '/agent/{agent_id}/network/dhcp-device-discovery',  hasBody: true },
};
